### PR TITLE
Update to work with latest rust and rust-sdl2

### PR DESCRIPTION
**Pull request by bdero**
This fixes the build against the latest rust nightly.

Tested working against `rustc 1.0.0-nightly (6cf3b0b74 2015-03-30) (built 2015-03-31)`!

### CODE REVIEW

**Comment by jdeseno** [comment]
Sorry for the delay. LGTM :+1: 
Would you remove the `git = ...` attribute from the `Cargo.toml`? This project will use what's available on crates.io. (SDL2 has been updated to 0.0.34, so we should be good.)

**Comment by bdero** [comment]
Alright, just removed the git line. I'm about to build it against the April 2 nightly; I'll let you know how it goes.

**Comment by bdero** [comment]
@jdeseno I've been getting into rust-sdl2 again and got all of the examples working once more. The rust-sdl2 API as well as rust has changed a bit since the last wave, so the changes are bigger than before.
This is ready for review again and works against `rustc 1.1.0-nightly (c42c1e7a6 2015-05-02) (built 2015-05-02)`.

**Comment by jdeseno** [comment]
LGTM thank you

**Pull request merged**
