### PR TITLE
small event loop improvements

### PR DESCRIPTION
**Pull request by jesrui**

### CODE REVIEW

**Comment by jdeseno** [comment]
The previous loop was much simpler "loop until we receive a QuitEvent".
Your loop is better for technical reasons but, those reasons aren't explained in any way so the learner will have to make more effort to understand.

I like the `wait_iter` in place of `poll_iter`, thats simple enough. If you'd like to keep the other stuff, please comment in the code what that's for & rebase this PR.

**Comment by jesrui** [comment]
Ok, I have added some missing comments.

I tried to add the minimum number of lines to get a barely working event loop, which for me should include refreshing the window :-)

I have added the escape key because, while testing, I was tired of having to switch to the mouse to close the SDL window after launching it from the command line.

What do you think?

**Comment by jdeseno** [comment]
I think that works. Would you squash your commits?

**Comment by jesrui** [comment]
Done.

**Pull request merged**
